### ISSUE TITLE
Bug- handle sentence input

### ISSUE THREAD

**Issue by karunakc** [jagriti-bhatia/vigenere_cipher#2]
# Handle a sentence input from user
## Description
To accept sentence input from the user for encryption
## Resources
https://www.geeksforgeeks.org/vigenere-cipher/
<hr>
** Bounty points alloted : 50 **
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by jagriti-bhatia** [comment]
> Hey, could I please be assigned to this?

You've been assigned to the issue! Go ahead and work on it!

**Comment by shriyays** [comment]
> Hey could i please be assigned to this?

Hey, I'm so sorry for the late reply, you've been assigned to the issue. Hope you have fun working on it!:)

**Comment by Obsarian** [comment]
Can you please assign me this?

**Comment by anirudhRowjee** [comment]
Hey @CoderCatA5 @Obsarian, we're running into some issues right now which prevent us from assigning these issues to you. 
However, please feel free to submit your PRs nonetheless! We'll consider them as valid submissions.

**Comment by Obsarian** [comment]
Is it possible to reassign me this?
